-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS courses (
     "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
     "name" VARCHAR(255) NOT NULL,
     "students" INTEGER ARRAY,
     "homeworks" INTEGER ARRAY,
     "categories" INTEGER ARRAY,
     "image" INTEGER,
     PRIMARY KEY("id")
);

INSERT INTO courses (name, students, homeworks, steps) 
VALUES 
    ('Course1', '{1}', '{1, 2, 3}', '{1, 2, 3}'),
    ('Course1', '{1, 2}', '{1, 2, 3}', '{1, 2, 3}'),
    ('Course1', '{2}', '{1, 2, 3}', '{1, 2, 3}');


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS courses;
-- +goose StatementEnd
