-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS courses (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"students" INTEGER ARRAY,
	"homeworks" INTEGER ARRAY,
	"steps" INTEGER ARRAY,
	PRIMARY KEY("id")
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS courses;
-- +goose StatementEnd
