-- +goose Up

CREATE TABLE IF NOT EXISTS courses (
     "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
     "name" VARCHAR(255) NOT NULL,
     "students" INTEGER ARRAY,
     "homeworks" INTEGER ARRAY,
     "categories" INTEGER ARRAY,
     "image" INTEGER,
     PRIMARY KEY("id")
);

-- +goose Down
DROP TABLE IF EXISTS courses;

