-- +goose Up
CREATE TABLE IF NOT EXISTS "lessons" (
     "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
     "teacher" INTEGER NOT NULL,
     "text" TEXT,
     "createdAt" TIMESTAMP NOT NULL,
     "steps" INTEGER ARRAY,
     "image" INTEGER,
     "name" TEXT NOT NULL,
     "usersPassed" INTEGER ARRAY,
     PRIMARY KEY("id")
);

INSERT INTO "lessons" ("teacher", "text", "createdAt", "steps", "image", "name", "usersPassed")
VALUES
  (1, 'Intro lesson text', now(), '{1,2}'::integer[], 1, 'Intro to Go', '{1}'::integer[]),
  (2, 'Second lesson text', now(), '{3}'::integer[], 2, 'Advanced topics', '{1,2}'::integer[]);


-- +goose Down
DROP TABLE IF EXISTS lessons;
