-- +goose Up
CREATE TABLE IF NOT EXISTS "lessons" (
     "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
     "teacher" INTEGER NOT NULL,
     "text" TEXT,
     "createdAt" TIMESTAMP NOT NULL,
     "steps" INTEGER ARRAY,
     "image" INTEGER,
     "name" TEXT NOT NULL,
     "usersPassed" INTEGER ARRAY,
     PRIMARY KEY("id")
);

-- +goose Down
DROP TABLE IF EXISTS lessons;
