-- +goose Up
CREATE TABLE IF NOT EXISTS uploaded_homework (
   "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
   "user" INTEGER NOT NULL,
   "homework" INTEGER NOT NULL,
   "files" INTEGER ARRAY NOT NULL,
   PRIMARY KEY("id")
);

-- +goose Down
DROP TABLE IF EXISTS uploaded_homework;
