-- +goose Up
CREATE TABLE IF NOT EXISTS categories (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "lessons" INTEGER ARRAY NOT NULL,
    "name" TEXT NOT NULL,
    PRIMARY KEY("id")
);

-- +goose Down
DROP TABLE IF EXISTS categories;
