-- +goose Up
CREATE TABLE IF NOT EXISTS notifications (
   "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
   "type" VARCHAR(50) NOT NULL,
   "date" TIMESTAMP NOT NULL,
   "dayOfWeek" VARCHAR(2) NOT NULL,
   "title" VARCHAR(100) NOT NULL,
   PRIMARY KEY("id")
);

INSERT INTO notifications ("type", "date", "dayOfWeek", "title")
VALUES
    ('deadline_future', now(), 'ВТ', 'Дедлайн по ДЗ по уроку 4'),
    ('deadline_past', now() - interval '2 days', 'ПН', 'Дедлайн по ДЗ по уроку 12 просрочен'),
    ('homework_graded', now() - interval '1 days', 'ВС', 'Преподователь оценил ваше ДЗ по уроку 14');

-- +goose Down
DROP TABLE IF EXISTS notifications;
