-- +goose Up
CREATE TABLE IF NOT EXISTS homework (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"text" TEXT,
	"createdAt" TIMESTAMP NOT NULL,
	"startsAt" TIMESTAMP NOT NULL,
	"endsAt" TIMESTAMP NOT NULL,
	"files" INTEGER ARRAY,
	PRIMARY KEY("id")
);

INSERT INTO homework (text, "createdAt", "startsAt", "endsAt", files)
VALUES
	('homework1', CURRENT_DATE - INTERVAL '2 days', CURRENT_DATE, CURRENT_DATE + INTERVAL '2 days', '{1, 2}'),
	('homework2', CURRENT_DATE - INTERVAL '1 days', CURRENT_DATE - INTERVAL '1 days', CURRENT_DATE + INTERVAL '1 days', '{1, 2}'),
	('homework3', CURRENT_DATE - INTERVAL '4 days', CURRENT_DATE - INTERVAL '1 days', CURRENT_DATE + INTERVAL '5 days', '{1, 2}');

-- +goose Down
DROP DATABASE IF EXISTS homework;
